### ISSUE TITLE
Change the square style when a piece is selected.

### ISSUE THREAD

**Issue by matheusmosca** [matheusmosca/simple-chess#4]
It would be nice if, when a player selects some piece, the squares which this piece can move receives a new style.
- The style can be like a little circle centralized in the center of the square
- The style should disappear if the player clicks in other square & when the piece moves
- It would be nice if squares that have enemy pieces receive a different style

Take a look at [lichess](https://lichess.org/) & [chess.com](https://www.chess.com/) for style insipiration.

The image below shows an example of what I want.

![style-example](https://user-images.githubusercontent.com/42419282/95273609-df63db00-0819-11eb-8e77-82f7c37a1a31.png)

**Comment by aaronleopold** [comment]
Hey there, I can give this a shot if you'd like. I just looked over some of the code and it looks really clean!

**Comment by matheusmosca** [comment]
Hi @aaronleopold, I'll assign you :smiley:. I thought my code wasn't so good, thanks!

**Comment by aaronleopold** [comment]
Just a little update, I got the selected tile to highlight, going to work on getting the possible move tiles to have indicators later in the week! 😄

**Comment by shrinish123** [comment]
Hi, I was working on this, but I am stuck on a syntax error maybe.
I actually want to instantiate a object where I have the constructor name as a string, it is showing me a syntax error.
I tried searching online but wasn't able to solve this
I am newbie to typescript

![syntax_error](https://user-images.githubusercontent.com/56491104/95651878-cc4b5680-0b0a-11eb-9766-404f9e0a5e4f.png)

**Comment by matheusmosca** [comment]
Hi @shrinish123, I'll have a look at that. But this issue is already assigned :confused: 

Why do you want to instantiate an object like that? I think you won't need this to solve this issue.

**Comment by aaronleopold** [comment]
@matheusmosca did you have any specific styling in mind for possible movements that contain enemy pieces? I can try and mimic edge highlighting that they did in the photo you posted with the issue. Also, it would be an easy fix to correct but did you have any specific colors you wanted? I've just been use aquamarine as a placeholder during development.

That's the only thing left on my end to finish this issue! I should have a PR ready by the end of the today or tomorrow 🙂

**Comment by matheusmosca** [comment]
Hi @aaronleopold, I think the style that appears in the photo is good enough. But you can do something different as well if you want to.

Feel free to choose a color that you liked. I'll trust your choice. 

I'm looking forward to your pull request :eyes:

**Comment by aaronleopold** [comment]
I went ahead and made a PR https://github.com/matheusmosca/simple-chess/pull/18! I chose a dark green, but it may be tooooo dark looking back at it 😄
