### ISSUE TITLE
Show which player moves next

### ISSUE THREAD

**Issue by matheusmosca** [matheusmosca/simple-chess#5]
At this moment, the players can't know who plays next. 

The image below shows an easy way to resolve that, the squares of the last movement are spotted with a different style.

You can also create a card container for each player and show there which one moves next.

It would be nice if someone implements both cases.

Good chess websites for inspiration:
- [lichess](https://lichess.org/)
- [chess.com](https://www.chess.com/)

![Screenshot_2020-10-07 Correspondence Chess • Anon vs A I level 1](https://user-images.githubusercontent.com/42419282/95391974-5ce92300-08ce-11eb-9f65-85299502dba8.png)

**Comment by sajeevan16** [comment]
Please assign this problem

**Comment by matheusmosca** [comment]
Sure :thumbsup:

**Comment by sajeevan16** [comment]
Check out my [PR](https://github.com/matheusmosca/simple-chess/pull/8)

**Comment by rlodhiya2502** [comment]
I have also created a PR. Please have a look. Using Cursor indicator.

**Comment by ghsayan** [comment]
I would like to add this feature.

**Comment by sajeevan16** [comment]
Show which player moves next #8

**Comment by sajeevan16** [comment]
[Show which player moves next ](#8)
