### ISSUE TITLE
Create gulp web server task

### ISSUE THREAD

**Issue by matheusmosca** [matheusmosca/simple-chess#6]
At this moment, the gulp watch task doesn't open ./dist/index.html in the browser, and I need to do it manually. 

Also, I need to reload the browser whenever a file changed.

### Procedure
- Gulp watch task should start a web server
- Modify a file should reload the browser

[gulp-webserver](https://www.npmjs.com/package/gulp-webserver) can be helpful.

**Comment by VinWare** [comment]
I can look into this, pls assign

**Comment by matheusmosca** [comment]
Hi, I'll assign you.

**Comment by matheusmosca** [comment]
Closed by #16
